# Generated by Django 5.0.1 on 2024-02-05 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('division', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districName', models.CharField(max_length=20)),
                ('divisionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='division.divisions')),
            ],
        ),
    ]
